name: CI Pipeline

on:
  push:
    branches:
      - "**"

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r payment/requirements.txt
          pip install pytest

      - name: Create .env file
        run: |
          echo "REDIS_HOST=localhost" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_PASSWORD=" >> .env

      - name: Run tests
        run: pytest